### ISSUE TITLE
Adicionar tópico: Cumprimentar

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#41]
Inserir conteúdo para que o Bot seja capaz de cumprimentaro usuário.

**Tarefas**
- [x] Criar conteúdo
- [x] Inserir conteúdo referente a ação de cumprimentar no bot

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by KahCosta** [comment]
[Estudo sobre criação de intents eficientes](https://github.com/lappis-unb/tais/wiki/Intents-Eficientes)

**Comment by pedroeagle** [comment]
pretendo começar agora a implementação dessa issue. eu crio uma branch pra issue e dou fork do repo do boilerplate?

**Comment by Lucas362** [comment]
O padrão para desenvolvimento desta issue será disponibilizado segunda-feira. Para a execução desta, recomendo que realize a criação da personalidade do bot (issue #39).

**Comment by Lucas362** [comment]
Padrão definido. O fork foi feito, então você só precisa criar sua branch a partir da devel e correr pro abraço. (lembrando que documentação é feito a partir da gh-pages)

**Comment by pedroeagle** [comment]
como utilizo o docker? crio primeiramente a branch e depois o docker?

**Comment by Lucas362** [comment]
Opa, você primeiro cria a brach na qual irá trabalhar, seguindo nossa [política de branchs](https://fga-eps-mds.github.io/2019.1-Aix/2019/03/29/gcs/) presente em nosso GCS.
Depois você pode seguir o [tutorial do boilerplate](https://github.com/lappis-unb/rasa-ptbr-boilerplate) presente em seu readme para utilizá-lo em nosso projeto.
Logo mais esse passo a passo será disponibilizado em nosso repositório.
Boa sorte com o trabalho!

**Comment by pedroeagle** [comment]
> Opa, você primeiro cria a brach na qual irá trabalhar, seguindo nossa [política de branchs](https://fga-eps-mds.github.io/2019.1-Aix/2019/03/29/gcs/) presente em nosso GCS.
> Depois você pode seguir o [tutorial do boilerplate](https://github.com/lappis-unb/rasa-ptbr-boilerplate) presente em seu readme para utilizá-lo em nosso projeto.
> Logo mais esse passo a passo será disponibilizado em nosso repositório.
> Boa sorte com o trabalho!

certo! agradeço.

**Comment by pedroeagle** [comment]
ERROR: for 20191aix_rocketchat_1  Cannot start service rocketchat: driver failed programming external connectivity on endpoint 20191aix_rocketchat_1 (f88cb18dece5c8295d3a60a5074cde56493acc380df828aa474f467da1c4a119): Bind for 0.0.0.0:3000 failed: port is already allocated

esse erro me impediu de finalizar o primeiro passo de utilização do boilerplate. como proceder?

**Comment by Lucas362** [comment]
Erro indica que a porta que o rocket chat quer usar já está em uso por alguém.
Nesse caso, eu recomendo q acesse localhost:3000 no seu navagedor, veja o serviço que está utilizando a porta e, caso o processo seja desnecessário, mate o processo que está utilizando a porta. Ou, mude a porta de um dos processos que usam a porta 3000 (o próprio rocket chat ou o serviço que já está utilizando a porta)

**Comment by Lucas362** [comment]
Outra possibilidade é o próprio rocket chat já estar utilizando a porta, neste caso, pule o primeiro passo do tutorial. :wink:

**Comment by pedroeagle** [comment]
> Erro indica que a porta que o rocket chat quer usar já está em uso por alguém.
> Nesse caso, eu recomendo q acesse localhost:3000 no seu navagedor, veja o serviço que está utilizando a porta e, caso o processo seja desnecessário, mate o processo que está utilizando a porta. Ou, mude a porta de um dos processos que usam a porta 3000 (o próprio rocket chat ou o serviço que já está utilizando a porta)

realmente. verifiquei aqui e o rocketchat está rodando na 0.0.0.0:3000

**Comment by pedroeagle** [comment]
> Outra possibilidade é o próprio rocket chat já estar utilizando a porta, neste caso, pule o primeiro passo do tutorial.

pulei pro segundo passo e está funcionando corretamente até agora. no total, quase 1gb de download :o

**Comment by pedroeagle** [comment]
depois de muita espera, tive esse erro no segundo comando: 

20191aix_actions_1 is up-to-date
Starting 20191aix_bot_1 ... 
Starting 20191aix_bot_1 ... done
Attaching to 20191aix_bot_1
bot_1         | 2019-04-04 12:42:21,400 :: Bot Config :: INFO :: ===== Automatic env configuration =====
bot_1         | Traceback (most recent call last):
bot_1         |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
bot_1         |     (self._dns_host, self.port), self.timeout, **extra_kw)
bot_1         |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
bot_1         |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
bot_1         |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
bot_1         |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
bot_1         | socket.gaierror: [Errno -2] Name or service not known
bot_1         | 
bot_1         | During handling of the above exception, another exception occurred:
bot_1         | 
bot_1         | Traceback (most recent call last):
bot_1         |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
bot_1         |     chunked=chunked)
bot_1         |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
bot_1         |     conn.request(method, url, **httplib_request_kw)
bot_1         |   File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
bot_1         |     self._send_request(method, url, body, headers, encode_chunked)
bot_1         |   File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
bot_1         |     self.endheaders(body, encode_chunked=encode_chunked)
bot_1         |   File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
bot_1         |     self._send_output(message_body, encode_chunked=encode_chunked)
bot_1         |   File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
bot_1         |     self.send(msg)
bot_1         |   File "/usr/local/lib/python3.6/http/client.py", line 964, in send
bot_1         |     self.connect()
bot_1         |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
bot_1         |     conn = self._new_conn()
bot_1         |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
bot_1         |     self, "Failed to establish a new connection: %s" % e)
bot_1         | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f106438ad30>: Failed to establish a new connection: [Errno -2] Name or service not known
bot_1         | 
bot_1         | During handling of the above exception, another exception occurred:
bot_1         | 
bot_1         | Traceback (most recent call last):
bot_1         |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
bot_1         |     timeout=timeout
bot_1         |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
bot_1         |     _stacktrace=sys.exc_info()[2])
bot_1         |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
bot_1         |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
bot_1         | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='rocketchat', port=3000): Max retries exceeded with url: /api/v1/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f106438ad30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
bot_1         | 
bot_1         | During handling of the above exception, another exception occurred:
bot_1         | 
bot_1         | Traceback (most recent call last):
bot_1         |   File "/scripts/bot_config.py", line 252, in <module>
bot_1         |     user_header = get_authentication_token()
bot_1         |   File "/scripts/bot_config.py", line 118, in get_authentication_token
bot_1         |     response = requests.post(host + path, data=json.dumps(login_data))
bot_1         |   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 116, in post
bot_1         |     return request('post', url, data=data, json=json, **kwargs)
bot_1         |   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
bot_1         |     return session.request(method=method, url=url, **kwargs)
bot_1         |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
bot_1         |     resp = self.send(prep, **send_kwargs)
bot_1         |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
bot_1         |     r = adapter.send(request, **kwargs)
bot_1         |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
bot_1         |     raise ConnectionError(e, request=request)
bot_1         | requests.exceptions.ConnectionError: HTTPConnectionPool(host='rocketchat', port=3000): Max retries exceeded with url: /api/v1/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f106438ad30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
20191aix_bot_1 exited with code 1

como proceder?

**Comment by Lucas362** [comment]
Opa, por enquanto tente executar os seguintes comandos:
`sudo docker-compose run --rm bot make train`
`sudo docker-compose run --rm bot make run-console`

Eles vão dar um run no seu docker, caso tenha problemas ao executá-los mande aqui, e tomaremos outro caminho

**Comment by pedroeagle** [comment]
**### Sobre a _issue_:**

Na presente _issue_  será adicionada apenas uma frase para a _utter_ cumprimentar. A frase será:

         "Olá, eu sou Aix 

          Bée

          Sua assistente aqui no Jupyter Notebook

          Em que posso te ajudar?"

Após reuniões para definir a personalidade do _bot_, decidiu-se que se trata de uma cabra. Assim sendo foi adicionada a onomatopeia "Bée" ao cumprimento.
Como o _bot_ auxiliará na programação em Python no caderno virtual "_Jupyter Notebook_", a chamamos de assistente do usuário no _Jupyter Notebook_.

**### Arquivos alterados:**

O 'domain.yml' foi o único arquivo alterado. Foram removidas as frases padrão da _utter_ 'cumprimentar' do [Boilerplate](https://github.com/lappis-unb/rasa-ptbr-boilerplate) e adicionada a _utter_ mencionada acima. Não foram adicionadas _intents_ ao arquivo 'data/stories/main.md'.
